default_platform(:ios)

platform :ios do
  desc "Build and archive iOS app"
  lane :build do
    build_app(
      workspace: "AstroRoshni.xcworkspace",
      scheme: "AstroRoshni",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "AstroRoshni.ipa"
    )
  end
end
