import React from 'react';
import { Link } from 'react-router-dom';
import NavigationHeader from '../Shared/NavigationHeader';

const TermsPage = () => {
  return (
    <div style={{
      minHeight: '100vh',
      background: 'linear-gradient(135deg, #f8f9fa 0%, #e9ecef 50%, #dee2e6 100%)',
      fontFamily: 'Arial, sans-serif'
    }}>
      <NavigationHeader />
      <div style={{ padding: '220px 20px 60px 20px', maxWidth: '800px', margin: '0 auto' }}>
        <h1 style={{ color: '#e91e63', marginBottom: '10px' }}>Terms and Conditions of Usage for AstroRoshni</h1>
        <p style={{ color: '#666', marginBottom: '30px' }}><em>Last Updated:</em> June 7, 2026</p>

        <section style={{ marginBottom: '30px' }}>
          <p>
            Welcome to <strong>AstroRoshni</strong>! These Terms and Conditions (&quot;Terms&quot;, &quot;Agreement&quot;) govern your access to and use of the AstroRoshni website, mobile applications, and all associated services (collectively referred to as the &quot;Platform&quot;). The Platform is owned and operated by <strong>Apeiron Logic LLP</strong> (&quot;Company&quot;).
          </p>
          <p>
            By accessing, browsing, downloading, or using the Platform, you (&quot;User&quot;, &quot;Member&quot;, &quot;Customer&quot;) agree to be bound by these Terms. If you do not agree with any part of these Terms, you must immediately cease using the Platform.
          </p>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#333' }}>1. Important Definitions</h2>
          <ul>
            <li><strong>&quot;AstroRoshni&quot; / &quot;We&quot; / &quot;Us&quot; / &quot;Our&quot;:</strong> Refers to Apeiron Logic LLP, the AstroRoshni platform, its artificial intelligence (AI) architecture, owners, directors, and employees.</li>
            <li><strong>&quot;User&quot; / &quot;You&quot;:</strong> Any person who accesses the Platform.</li>
            <li><strong>&quot;Services&quot;:</strong> The AI-generated astrological content, reports, data, and interactive AI sessions provided on the Platform.</li>
          </ul>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#333' }}>2. Eligibility</h2>
          <p>
            By using the Platform, you represent and warrant that you are at least 18 years of age and legally competent to form a binding contract under the Indian Contract Act, 1872.
          </p>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#333' }}>3. Account Registration and Security</h2>
          <ul>
            <li><strong>Accurate Information:</strong> You agree to provide accurate, current, and complete birth data to ensure precise AI analysis.</li>
            <li><strong>Account Security:</strong> You are solely responsible for maintaining the confidentiality of your account credentials.</li>
          </ul>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#333' }}>4. Description of Services &amp; &quot;AI Content&quot; Acknowledgement</h2>
          <ul>
            <li>
              <strong>Purely AI Platform:</strong> AstroRoshni provides high-precision astrological calculations and analysis exclusively through artificial intelligence. <strong>AstroRoshni is purely an AI platform with no human astrologers on board and does not operate as an astrologer marketplace.</strong>
            </li>
            <li>
              <strong>Nature of AI &amp; Astrology:</strong> While our platform utilizes advanced computational algorithms to ensure the mathematical precision of astrological charts, astrology itself does not possess standardized scientific consensus. Therefore, the interpretive reports and AI interactions are provided strictly for entertainment, personal reflection, and spiritual guidance.
            </li>
            <li>
              <strong>Automated Generation:</strong> Because the content is dynamically generated by AI, AstroRoshni does not guarantee that the text will be entirely free of algorithmic anomalies or &quot;hallucinations.&quot;
            </li>
          </ul>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#333' }}>5. Payments, Wallet, and Fair Refund Policy</h2>
          <p>All Paid Services on AstroRoshni operate on a prepaid &quot;Wallet&quot; or pay-per-report model.</p>
          <ul>
            <li><strong>Wallet Recharges:</strong> Wallet balances are non-transferable and cannot be withdrawn to bank accounts.</li>
            <li>
              <strong>General Refund Policy:</strong> Due to the digital nature of the service, once an AI interaction is completed or a report is successfully delivered based on the data you provided, refunds will not be issued based on disagreement with the astrological interpretation.
            </li>
            <li>
              <strong>Deficiency in Service (Exceptions for Refund):</strong> A refund or wallet credit <em>will</em> be provided if you experience a technical deficiency, including:
              <ul>
                <li>System crashes or network failures that deduct wallet balance without delivering the service.</li>
                <li>The AI generates heavily corrupted, garbled, or entirely irrelevant text (algorithmic failure).</li>
              </ul>
            </li>
            <li>
              To claim a refund under these conditions, you must open a ticket in the Support Section or write to{' '}
              <a href="mailto:help@astroroshni.com" style={{ color: '#e91e63', fontWeight: 'bold' }}>help@astroroshni.com</a>{' '}
              within 48 hours of the incident.
            </li>
          </ul>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#333' }}>6. User Conduct and AI Guardrails</h2>
          <p>The AstroRoshni AI is strictly programmed with safety guardrails to refuse certain topics. You agree <strong>NOT</strong> to:</p>
          <ul>
            <li>Attempt to reverse-engineer, &quot;jailbreak,&quot; or manipulate the AI prompts to bypass safety protocols.</li>
            <li>Use the Platform to seek medical diagnoses, financial investment advice, or legal counsel.</li>
            <li>
              Ask questions relating to the gender determination of a fetus, which is strictly prohibited under the Pre-Conception and Pre-Natal Diagnostic Techniques (PCPNDT) Act, 1994.
            </li>
          </ul>
          <p>
            If a User intentionally manipulates the AI to produce prohibited content, the User bears sole legal responsibility for that output, and their account will be terminated.
          </p>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#333' }}>7. Strict Disclaimer of Warranties</h2>
          <ul>
            <li>
              <strong>Specialist advice is strongly advocated</strong> for all questions asked on the AstroRoshni platform. The AI-generated astrological advice or insights are <strong>not</strong> a substitute for professional, legal, financial, medical, or psychological advice.
            </li>
            <li>
              <strong>Medical &amp; Mental Health:</strong> If you are facing severe mental distress, depression, or suicidal thoughts, please consult a qualified medical professional or a suicide prevention helpline immediately. Do not rely on AI-generated predictions for mental health crises.
            </li>
          </ul>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#333' }}>8. Limitation of Liability and Financial Cap</h2>
          <p>
            To the maximum extent permitted by applicable Indian law, Apeiron Logic LLP shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, revenues, data, or emotional distress resulting from your reliance on the AI Services.
          </p>
          <ul>
            <li>
              <strong>Strict Liability Cap:</strong> In no event shall the total, aggregate liability of AstroRoshni and Apeiron Logic LLP for any claim arising out of or relating to these Terms or the Services exceed the actual INR amount paid by the User for the specific report or interactive session giving rise to the dispute.
            </li>
          </ul>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#333' }}>9. Intellectual Property Rights</h2>
          <p>
            All content on the Platform, including AI models, algorithms, codebase, graphics, and generated reports, is the exclusive property of Apeiron Logic LLP and is protected by copyright and trademark laws.
          </p>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#333' }}>10. Privacy Policy and DPDP Compliance</h2>
          <p>
            Your use of the Platform involves the processing of personal and astrological data. By accepting these Terms, you explicitly consent to our data processing practices as outlined in our{' '}
            <Link to="/policy" style={{ color: '#e91e63', fontWeight: 'bold' }}>Privacy Policy</Link>, which is compliant with the Digital Personal Data Protection (DPDP) Act, 2023.
          </p>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#333' }}>11. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless Apeiron Logic LLP, its directors, and employees from any claims, damages, or legal expenses arising out of your violation of these Terms, particularly regarding the intentional misuse of the AI to generate prohibited content.
          </p>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#333' }}>12. Governing Law and Dispute Resolution</h2>
          <ul>
            <li><strong>Jurisdiction:</strong> These Terms shall be governed by the laws of India.</li>
            <li>
              <strong>Dispute Resolution:</strong> Any disputes arising out of these Terms shall be subject to the exclusive jurisdiction of the courts located in New Delhi, India.
            </li>
          </ul>
        </section>

        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#333' }}>13. Contact and Support</h2>
          <p>For any questions, grievances, technical issues, or support:</p>
          <ul>
            <li><strong>Support Tickets:</strong> Support can be obtained by opening a ticket in the Support Section of the platform.</li>
            <li>
              <strong>Email:</strong> You may also write to us at{' '}
              <a href="mailto:help@astroroshni.com" style={{ color: '#e91e63', fontWeight: 'bold' }}>help@astroroshni.com</a>.
            </li>
            <li><strong>Entity:</strong> Apeiron Logic LLP</li>
            <li>
              <strong>Address:</strong> S1-41, Vatika Signature Vill, Narsinghpur, Kherki Daula Police Station, Narsinghpur, Gurgaon- 122004, Haryana, India
            </li>
          </ul>
        </section>

        <hr style={{ border: 'none', borderTop: '1px solid #ccc', margin: '40px 0' }} />

        <p style={{ color: '#666', fontSize: '0.9rem' }}>
          See also: <Link to="/policy" style={{ color: '#e91e63' }}>Privacy Policy</Link>
        </p>
      </div>
    </div>
  );
};

export default TermsPage;
