"""Original operational summaries of BPHS Chapter 24 placement results.

These are concise paraphrases for computation and display, not a reproduced translation.
"""

VERSE_OUTCOMES = {
    1: ('physical resilience and initiative', 'an intelligent but changeable disposition', 'strong relationship appetite'),
    2: ('capacity for learning and material gain', 'good conduct and respect', 'strong family and relationship involvement'),
    3: ('courage and self-made progress', 'intelligence, confidence and material capacity'),
    4: ('support from parents and family', 'comfort through home and relatives', 'an attractive and pleasure-seeking nature'),
    5: ('mixed ease concerning children', 'recognition and influence', 'an assertive or quick-tempered nature'),
    6: ('physical comfort can be reduced when the lord is afflicted', 'conflict and opponents become important life lessons'),
    7: ('life direction is strongly tied to partnership and public dealings', "results vary sharply with the lord's nature and strength"),
    8: ('interest in difficult or hidden knowledge', 'health and anger require care', 'risk-taking or questionable conduct is cautioned'),
    9: ('fortune, skill and persuasive speech', 'religious or devotional inclination', 'support through family and resources'),
    10: ('self-earned advancement', 'public recognition and reputation', 'support connected with father or authority'),
    11: ('recurring gains and recognition', 'social standing and accomplishment', 'strong relationship involvement'),
    12: ('physical ease and expenditure require care when benefic support is absent', 'anger and wastefulness are cautioned'),
    13: ('wealth and children can become prominent', 'family friction or hardness is possible', "work may serve other people's aims"),
    14: ('strong wealth-building potential', 'pride and family complexity', 'ease concerning children may be reduced'),
    15: ('courage, intelligence and skill', 'results become constructive with benefic association and harsher with malefic association'),
    16: ('property and broad material comfort', 'exaltation with Jupiter can raise status markedly'),
    17: ('wealth-building ability', 'children may also be oriented toward earning and resources'),
    18: ('money through competition when supported', 'loss through opponents when afflicted', 'the lower legs may be physically sensitive'),
    19: ('money may come through partnership', 'healing or medical work may become relevant', 'affliction can disturb marital conduct'),
    20: ('land or accumulated assets', 'reduced ease in marriage', 'limited support from an elder sibling'),
    21: ('wealth through effort and skill', 'childhood health sensitivity followed by improvement', 'pilgrimage or religious observance'),
    22: ('learning, honour and substantial resources', 'strong sensual or relationship appetite', 'ease from children may be reduced'),
    23: ('broad gains through steady effort', 'honour and public reputation'),
    24: ('financial leakage despite initiative', "interest in other people's resources", 'reduced ease concerning the eldest child'),
    25: ('self-earned resources and courage', 'worshipful inclination', 'practical intelligence may exceed formal education'),
    26: ('reduced initiative and satisfaction', 'comfort-seeking or possessive tendencies require care'),
    27: ('support from siblings', 'resources, children and general happiness are favoured'),
    28: ('comfort, intelligence and wealth', 'the spouse relationship may require discernment and care'),
    29: ('children and virtue are supported', 'malefic influence can make partnership difficult'),
    30: ('conflict with siblings or maternal relatives', 'financial capacity can still be strong'),
    31: ('service to authority or institutions', 'early difficulties can improve later in life'),
    32: ('livelihood through service', 'unlawful conduct and conflict with authority require caution'),
    33: ('reduced paternal ease', 'fortune through spouse or women', 'support concerning children'),
    34: ('comfort and self-made resources', 'problematic romantic involvement requires caution'),
    35: ('gains through trade', 'practical intelligence and courage', 'work in service to others'),
    36: ('expenditure on unhelpful actions', 'difficulty connected with father', 'fortune through a woman'),
    37: ('education, virtues and refinement', 'property, vehicles and land', 'maternal support'),
    38: ('material comfort, family life and standing', 'initiative with a calculating streak'),
    39: ('courage and self-earned wealth', 'support through helpers', 'generosity and health resilience'),
    40: ('authority and strong resources', 'skill, learning and domestic happiness'),
    41: ('happiness, popularity and virtue', 'devotional inclination', 'self-earned wealth'),
    42: ('reduced maternal ease', 'anger and troubled conduct', 'emotional or physical discomfort'),
    43: ('high learning or education', 'distance from inherited wealth', 'difficulty expressing oneself publicly'),
    44: ('reduced domestic and parental comfort', 'property and inner security may require effort'),
    45: ('broad happiness and public affection', 'devotion, virtue and honour'),
    46: ('recognition through authority', 'enjoyment and unusual knowledge', 'capacity for self-control'),
    47: ('generosity and helpfulness', 'a health concern may remain private or difficult to identify'),
    48: ('reduced domestic comfort', 'indolence, poor habits or confused judgment are cautioned'),
    49: ('learning and concern with children', "possessiveness or crooked dealing with others' resources is cautioned"),
    50: ('wealth, family support and reputation', 'strong connection with spouse and children'),
    51: ('attachment to siblings and personal projects', 'gossip or miserliness is cautioned'),
    52: ('intelligence, wealth and maternal support', 'potential for counsel, teaching or responsible office'),
    53: ('children are supported under benefic influence and obstructed under malefic influence', 'virtue and friendship remain important'),
    54: ('strain or conflict involving children', 'adoption or another path to parenthood may become relevant'),
    55: ('honour, religious inclination and support through children', 'helpfulness to others'),
    56: ('limited ease concerning children', 'respiratory sensitivity and anger require care'),
    57: ('distinction through children, scholarship or authorship', 'public reputation and family legacy'),
    58: ('leadership and recognition through work', 'learning and comforts'),
    59: ('learning, writing and skill', 'resources and support through children'),
    60: ('reduced ease from biological children', 'adoption or another path to parenthood may become relevant'),
    61: ('health sensitivity alongside courage and recognition', "conflict with one's own circle", 'wealth and capability remain possible'),
    62: ('courage, reputation and skilled speech', 'work or residence away from birthplace'),
    63: ('anger and reduced courage', 'conflict with siblings', 'difficulty with helpers'),
    64: ('reduced maternal ease', 'jealousy or restless thinking', 'strong material capacity'),
    65: ('fluctuating finances', 'conflict involving children or friends', 'self-interest mixed with kindness'),
    66: ('conflict within the family circle', 'greater friendliness outside it', 'moderate material comfort'),
    67: ('partnership happiness may be reduced', 'reputation, courage and resources can remain strong'),
    68: ('health sensitivity and rivalry', "desire for others' resources or relationships is cautioned"),
    69: ('trade involving hard materials', 'professional gains and losses may fluctuate'),
    70: ('recognition and skilled speech', 'distance from father', 'comfort or work in foreign places'),
    71: ('gains through competitors or disputes', 'courage and virtues', 'reduced ease concerning children'),
    72: ('expenditure through harmful habits', 'hostility toward learned people or living beings is cautioned'),
    73: ('relationships strongly shape identity', 'skill with reduced steadiness', 'wind-related physical sensitivity requires care'),
    74: ('resources through spouse or partnership', 'relationship multiplicity or delay in action is cautioned'),
    75: ('difficulty or delay concerning sons', 'daughters may be more prominent'),
    76: ('an independent spouse', 'truthfulness, intelligence and religion', 'dental sensitivity'),
    77: ('honour, happiness and strong resources', 'virtues expressed through creativity or children'),
    78: ('illness or conflict involving spouse', 'anger and reduced domestic happiness'),
    79: ('marital happiness and capable partnership', 'wind-related physical sensitivity requires care'),
    80: ('reduced marital ease', 'spouse health or conduct may require care'),
    81: ('many relationship contacts or undertakings', 'attachment to spouse remains strong'),
    82: ('a strong-willed or noncompliant spouse', 'religion, wealth and children can be supported'),
    83: ('gains through spouse', 'daughters may be more prominent while ease concerning sons may be reduced'),
    84: ('expense and financial restraint through marriage', 'livelihood connected with clothing', 'spouse may spend freely'),
    85: ('physical comfort and wound vulnerability require care', 'conflict with religion or learned authorities is cautioned'),
    86: ('reduced bodily strength and limited accumulation', 'lost resources may be hard to recover'),
    87: ('reduced sibling support', 'low initiative and limited help from servants or staff'),
    88: ('reduced maternal, property and domestic support', 'betrayal of friends is cautioned'),
    89: ('limited discernment or fewer children', 'longevity and wealth can nevertheless be supported'),
    90: ('victory over opponents alongside health sensitivity', 'childhood danger connected with water or snakes requires caution'),
    91: ('relationship multiplicity', 'business decline becomes a concern when the lord is joined by a malefic'),
    92: ('longevity is supported when the lord is strong', 'weakness reduces the result and worsens conduct'),
    93: ('conflict with religion or ethics', "difficult spouse conduct and taking others' resources are cautioned"),
    94: ('reduced paternal and career ease unless a benefic aspects the lord', 'gossip is cautioned'),
    95: ('malefic association reduces wealth and early happiness', 'benefic association supports longevity and later improvement'),
    96: ('expenditure on harmful activity and reduced longevity, especially with added malefic influence',),
    97: ('fortune, virtue and public respect', 'learning, charm and recognition'),
    98: ('learning, wealth and popularity', 'support through spouse and children'),
    99: ('support from siblings', 'wealth, virtue and personal appeal'),
    100: ('property, vehicles and broad comfort', 'wealth and devotion to mother'),
    101: ('children, prosperity and learning', 'respect for elders, courage and charity'),
    102: ('limited fortune and maternal-relative support', 'recurring conflict or obstacles'),
    103: ('fortune improves after marriage', 'virtue and reputation'),
    104: ('reduced prosperity and limited support from elder siblings',),
    105: ('strong fortune, virtues and personal appeal', 'support from siblings'),
    106: ('leadership, high office or authority', 'virtue and public affection'),
    107: ('steadily increasing gains', 'respect for elders and meritorious conduct'),
    108: ('fortune may be spent or dispersed', 'auspicious expenditure and hospitality are emphasized'),
    109: ('learning, writing and fame', 'early health sensitivity with later improvement', 'steadily increasing resources'),
    110: ('wealth, virtue and honour', 'charity and support through father or elders'),
    111: ('support through siblings and helpers', 'courage, eloquence and truthfulness'),
    112: ('property, vehicles and domestic happiness', 'care for mother', 'wealth and virtue'),
    113: ('learning, happiness, resources and children',),
    114: ('reduced paternal support', 'skill with financial obstacles and opponents'),
    115: ('support through spouse', 'intelligence, virtue, eloquence and religion'),
    116: ('reduced professional activity despite longevity', 'criticism of others is cautioned'),
    117: ('high office, leadership or status', 'wealth and support concerning children'),
    118: ('professional skill, courage and truthfulness', 'respect for elders'),
    119: ('wealth, happiness and children', 'virtue, truth and contentment'),
    120: ('expense through government or institutions', 'fear of opponents and worry despite professional skill'),
    121: ('steady gains and resources', 'balanced outlook, writing and eloquence'),
    122: ('broad wealth and accomplishment', 'charity, religion and happiness'),
    123: ('professional skill and wealth', 'support from siblings', 'joint or gout-like pain may require care'),
    124: ('gains through maternal relatives', 'pilgrimage', 'property and domestic happiness'),
    125: ('education, virtue, religion and happiness',),
    126: ('health sensitivity and enemies', 'harshness and residence away from birthplace'),
    127: ("gains through spouse's family", 'generosity and virtue', 'strong spouse influence'),
    128: ('setbacks in undertakings alongside longevity', 'the possibility of outliving the spouse forms part of this indication'),
    129: ('fortune, skill and truthfulness', 'recognition and affluence'),
    130: ('recognition through authority', 'virtue, religion, intelligence and self-control'),
    131: ('success across undertakings', 'learning and happiness grow over time'),
    132: ('expenditure on good deeds', 'strong sensual and relationship involvement', 'foreign or unconventional associations'),
    133: ('heavy expenditure and weak constitution', 'phlegmatic sensitivity', 'limited wealth or education'),
    134: ('inauspicious expenditure alongside religion and sweet speech', 'virtues and happiness can coexist'),
    135: ('reduced sibling support', 'resentment of others and a self-protective orientation'),
    136: ('reduced maternal support', 'loss involving property, vehicles or home'),
    137: ('difficulty concerning children or education', 'pilgrimage and expenditure in pursuit of children'),
    138: ("conflict with one's own circle", 'anger, misery and problematic relationships are cautioned'),
    139: ('expense through spouse', 'reduced marital ease, learning and strength'),
    140: ('gains, agreeable speech and good qualities', 'moderate longevity'),
    141: ('disrespect toward elders and conflict with friends', 'strong self-interest'),
    142: ('expense through authority or government', 'moderate paternal support'),
    143: ('losses and dependence on others', 'occasional gains through other people'),
    144: ('heavy recurring expenditure', 'reduced physical ease', 'irritability and resentment are cautioned'),
}
