"""Representative acceptance cells for Instant Chat quality evaluation.

These are not keyword-routing rules. They are labelled, real-user questions
used to evaluate the multilingual LLM router, evidence plan and final answer.
"""

from __future__ import annotations

from typing import Any, Dict, List


def _case(case_id: str, question: str, operation: str, domain: str, *,
          language: str = "english", subject: str = "self",
          special_gate: str | None = None) -> Dict[str, Any]:
    return {
        "case_id": case_id, "question": question, "language": language,
        "operation": operation, "domain": domain, "subject": subject,
        "special_gate": special_gate,
    }


QUESTION_ACCEPTANCE_CASES: List[Dict[str, Any]] = [
    _case("fact-moon-sign", "What is my Moon sign?", "chart_fact", "general"),
    _case("fact-dasha-date", "When does my Mercury mahadasha begin?", "chart_fact", "general"),
    _case("fact-yoga-hi", "मेरी कुंडली में कौन से प्रमुख योग हैं?", "chart_fact", "general", language="hindi"),
    _case("explain-window", "Why did you call October the stronger marriage window?", "explanation", "marriage"),
    _case("challenge-claim", "You said Jupiter supports this. Show me exactly how.", "explanation", "general"),
    _case("nature-self", "How do I behave under pressure?", "trait_or_nature", "general"),
    _case("nature-spouse", "What kind of spouse am I likely to have?", "person_profile", "marriage", subject="spouse"),
    _case("nature-mother-in-law", "Meri saas ka nature kaisa hai?", "person_profile", "family", language="hinglish", subject="mother_in_law", special_gate="derived_house_disclosure"),
    _case("nature-child", "What will my first child's temperament be like?", "person_profile", "progeny", subject="first_child", special_gate="derived_house_disclosure"),
    _case("topic-career", "How is my career?", "topic_outlook", "career"),
    _case("topic-business", "How strong is my business potential right now?", "topic_outlook", "business"),
    _case("topic-marriage", "How is my married life?", "topic_outlook", "marriage"),
    _case("topic-wealth", "Why do my savings remain unstable?", "problem_diagnosis", "wealth"),
    _case("topic-property", "Is property ownership supported in my chart?", "capacity_or_fit", "property"),
    _case("topic-education", "Am I suited for higher studies?", "capacity_or_fit", "education"),
    _case("topic-spirituality", "What is the spiritual direction of my life?", "topic_outlook", "spirituality"),
    _case("period-career", "How is my career this year?", "period_outlook", "career"),
    _case("period-health-hi", "अगले छह महीने मेरी सेहत कैसी रहेगी?", "period_outlook", "health", language="hindi", special_gate="medical_safety"),
    _case("period-business", "How will my business perform over the next twelve months?", "period_outlook", "business"),
    _case("period-family", "How will family relations be this year?", "period_outlook", "family"),
    _case("period-father", "How is the coming year for my father's wellbeing?", "period_outlook", "father", subject="father", special_gate="derived_house_disclosure"),
    _case("topic-mother", "How is my relationship with my mother?", "topic_outlook", "mother", subject="mother", special_gate="derived_house_disclosure"),
    _case("topic-sibling", "Why is my relationship with my elder brother strained?", "problem_diagnosis", "siblings", subject="elder_brother", special_gate="derived_house_disclosure"),
    _case("when-marriage", "When will I get married?", "event_likelihood_or_timing", "marriage"),
    _case("when-promotion", "Will I get promoted this year?", "event_likelihood_or_timing", "career"),
    _case("when-job-hi", "मुझे नौकरी कब मिलेगी?", "event_likelihood_or_timing", "career", language="hindi"),
    _case("when-child", "When is childbirth most strongly supported?", "event_likelihood_or_timing", "progeny"),
    _case("when-property", "When can I buy my own house?", "event_likelihood_or_timing", "property"),
    _case("when-visa", "When is my foreign visa likely to move?", "event_likelihood_or_timing", "foreign"),
    _case("when-vehicle", "When is buying a vehicle supported?", "event_likelihood_or_timing", "vehicles"),
    _case("negative-job", "Am I likely to lose my job this year?", "event_likelihood_or_timing", "career", special_gate="no_fear_or_false_certainty"),
    _case("compare-job-business", "Should I continue my job or start a business?", "comparison_or_choice", "career", special_gate="option_specific_evidence"),
    _case("compare-study", "MBA in India or a master's abroad—which is better supported?", "comparison_or_choice", "education", special_gate="option_specific_evidence"),
    _case("diagnose-marriage", "Why do the same conflicts keep repeating in my marriage?", "problem_diagnosis", "marriage"),
    _case("diagnose-career", "Why has my career been stuck for two years?", "problem_diagnosis", "career"),
    _case("action-career", "What should I focus on professionally right now?", "action_guidance", "career"),
    _case("action-health", "What should I be careful about for my health?", "action_guidance", "health", special_gate="medical_safety"),
    _case("location-career", "Where should I move for career growth—India or abroad?", "location_recommendation", "career", special_gate="location_scope"),
    _case("compatibility", "Are Deepika and I compatible for marriage?", "compatibility", "marriage", special_gate="two_resolved_charts"),
    _case("muhurat", "Find the best time to register my company next month.", "muhurat_or_election", "business", special_gate="event_location_timezone"),
    _case("multipart", "When does Mercury dasha start and how will it affect my career?", "multi_part", "career", special_gate="answer_every_part"),
    _case("ambiguous-he", "Will he come back?", "event_likelihood_or_timing", "relationship", subject="unresolved", special_gate="clarify_subject_once"),
    _case("clarification-spouse", "spouse", "event_likelihood_or_timing", "marriage", subject="spouse", special_gate="merge_prior_turn"),
    _case("correction-husband", "Not my boyfriend—my husband.", "event_likelihood_or_timing", "marriage", subject="husband", special_gate="replace_prior_assumption"),
    _case("follow-up-why", "Why? And what happens after that?", "explanation", "general", special_gate="resolve_from_history"),
    _case("health-high-stakes", "Will this lump become cancer?", "period_outlook", "health", special_gate="medical_safety"),
    _case("topic-self", "What are my strongest and weakest personality patterns?", "trait_or_nature", "self"),
    _case("topic-life-purpose", "What kind of work is closest to my life purpose?", "topic_outlook", "life_purpose"),
    _case("when-employment", "When is my next job selection most likely?", "event_likelihood_or_timing", "employment"),
    _case("period-authority", "Will I receive more authority at work this year?", "period_outlook", "authority"),
    _case("when-job-change", "When is a job change better supported?", "event_likelihood_or_timing", "job_change"),
    _case("period-project", "How will my new product launch progress this year?", "period_outlook", "project"),
    _case("topic-income", "How stable is my salary and professional income?", "topic_outlook", "income"),
    _case("diagnose-debt", "Why am I struggling to clear my loans?", "problem_diagnosis", "debt"),
    _case("capacity-investment", "Does my chart support active investing?", "capacity_or_fit", "investment", special_gate="financial_safety"),
    _case("when-inheritance", "When may an inheritance or settlement move forward?", "event_likelihood_or_timing", "inheritance"),
    _case("period-separation", "Is this year supportive for reconciliation after separation?", "period_outlook", "separation"),
    _case("when-exams", "When is success in my competitive exam best supported?", "event_likelihood_or_timing", "exams"),
    _case("when-immigration", "When is permanent relocation abroad best supported?", "event_likelihood_or_timing", "immigration"),
    _case("location-wealth", "Which location is better for building wealth?", "location_recommendation", "location", special_gate="location_scope"),
    _case("period-mental-wellbeing", "How is my emotional wellbeing over the next six months?", "period_outlook", "mental_wellbeing", special_gate="medical_safety"),
    _case("when-surgery", "Which period is more supportive for my planned surgery?", "event_likelihood_or_timing", "surgery", special_gate="medical_safety"),
    _case("period-accident", "Is there a period of higher accident or injury vulnerability this year?", "period_outlook", "accident", special_gate="no_fear_or_false_certainty"),
    _case("period-recovery", "How is my recovery from this injury likely to progress?", "period_outlook", "recovery", special_gate="medical_safety"),
    _case("when-legal", "When is my court matter more likely to move?", "event_likelihood_or_timing", "legal"),
    _case("period-competition", "How will I fare against professional competition this year?", "period_outlook", "competition"),
    _case("topic-reputation", "How strong is my public reputation and visibility?", "topic_outlook", "reputation"),
    _case("when-government", "When is approval from the government more likely?", "event_likelihood_or_timing", "government"),
    _case("topic-friends", "How supportive is my network of friends?", "topic_outlook", "friends"),
    _case("capacity-creativity", "Where is my creative potential strongest?", "capacity_or_fit", "creativity"),
    _case("capacity-sports", "Does my chart support competitive sports?", "capacity_or_fit", "sports"),
    _case("capacity-research", "Am I suited for deep research work?", "capacity_or_fit", "research"),
    _case("diagnose-karma", "Why does this same life pattern keep repeating?", "problem_diagnosis", "karma"),
    _case("period-retirement", "How will the transition into retirement unfold?", "period_outlook", "retirement"),
    _case("when-adoption", "When is adoption most strongly supported?", "event_likelihood_or_timing", "adoption"),
    _case("muhurat-home", "Find a griha pravesh muhurat in Hisar next month.", "muhurat_or_election", "muhurat", special_gate="event_location_timezone"),
]
