"""Default broadcast nudge library and initial scheduling slots."""

DEFAULT_DAILY_SLOTS = ("07:00", "13:00", "17:00", "20:00")

DEFAULT_BROADCAST_NUDGES = [
    {"title": "The Billionaire Yoga", "body": "Do you have the exact planetary combination that made Mukesh Ambani rich? Find out before you make your next investment.", "category": "wealth_prosperity"},
    {"title": "Hidden Wealth in Your Chart", "body": "You might be sitting on a goldmine without knowing it. Check when your Dhan Yoga activates before the timeline passes!", "category": "wealth_prosperity"},
    {"title": "Is Your Luck Blocked?", "body": "Uncover the hidden dosha that’s secretly draining your bank account and learn the simple remedy to fix it today.", "category": "wealth_prosperity"},
    {"title": "The Lottery Placement", "body": "Some charts are destined for sudden windfalls. See if your 8th house holds the key to unexpected riches.", "category": "wealth_prosperity"},
    {"title": "Missed Opportunities", "body": "Your golden period for wealth creation might be slipping away right now. Check your current Mahadasha immediately.", "category": "wealth_prosperity"},
    {"title": "The Real Estate King", "body": "Will you own multiple properties or rent forever? Decode your 4th house secrets before finalizing your next house hunt.", "category": "wealth_prosperity"},
    {"title": "Debt-Free Destiny?", "body": "Stop stressing about loans. Find out exactly when the stars will align to clear your financial burdens once and for all.", "category": "wealth_prosperity"},
    {"title": "Stock Market Success", "body": "Is trading in your destiny, or is it a trap? Let your Kundli guide your next financial move before you risk it all.", "category": "wealth_prosperity"},
    {"title": "The Lakshmi Activation", "body": "Discover the exact year Goddess Lakshmi will bless your chart. Don't miss your ultimate prosperity window!", "category": "wealth_prosperity"},
    {"title": "Foreign Currency Fortune", "body": "Are you destined to earn in Dollars or Euros? Check your foreign settlement and international income yogas.", "category": "wealth_prosperity"},
    {"title": "Who is Your True Soulmate?", "body": "Stop swiping blindly! Your Kundli reveals the exact initial, profession, and meeting time of your future spouse.", "category": "love_relationships"},
    {"title": "The Heartbreak Placement", "body": "Are you dating the wrong zodiac sign? Find out why your past relationships failed and who you must avoid.", "category": "love_relationships"},
    {"title": "Marriage Delay?", "body": "Is a hidden Mangal Dosha pushing your wedding date away? Get your Kundli checked to remove unseen marital obstacles.", "category": "love_relationships"},
    {"title": "A Secret Admirer", "body": "Someone is secretly in love with you, and your planetary transits are giving away clues. Find out who it is!", "category": "love_relationships"},
    {"title": "Second Chance at Love?", "body": "Thought you missed your chance at a fairytale romance? Your chart predicts exactly when love will strike again.", "category": "love_relationships"},
    {"title": "Toxic Ties", "body": "Are karmic debts keeping you trapped in a toxic relationship? Uncover the hard truth hidden in your 7th house.", "category": "love_relationships"},
    {"title": "The \"Power Couple\" Yoga", "body": "Will you and your partner build an empire together like Virat and Anushka? Check your astrological compatibility score!", "category": "love_relationships"},
    {"title": "Arranged or Love?", "body": "The eternal dilemma! See what the stars have definitively written for your marriage style.", "category": "love_relationships"},
    {"title": "Cheating Placements", "body": "Does your partner's chart show fierce loyalty or wandering eyes? Decode their relationship houses now.", "category": "love_relationships"},
    {"title": "Wedding Bells 2026", "body": "Is this the year you finally tie the knot? Check your Jupiter transit before the upcoming wedding season ends!", "category": "love_relationships"},
    {"title": "The CEO Yoga", "body": "Were you born to be a boss or an employee? Unlock your ultimate leadership potential hidden in the 10th house.", "category": "career_business"},
    {"title": "Job vs. Business", "body": "Making the wrong choice could cost you years of success. See what career path your stars heavily favor.", "category": "career_business"},
    {"title": "Next Promotion Date", "body": "Stop guessing! Your astrology chart knows the exact month your boss will finally recognize your true worth.", "category": "career_business"},
    {"title": "Wrong Career Path?", "body": "Feeling stuck? You might be working against your natural planetary strengths. Find your true calling today.", "category": "career_business"},
    {"title": "The Fame Placement", "body": "Do you have the Bollywood or Influencer fame yoga? Discover if stepping into the spotlight is in your destiny.", "category": "career_business"},
    {"title": "Government Job Chances", "body": "Are you wasting time prepping for exams, or is a Sarkari Naukri written in your stars? Check your chances now!", "category": "career_business"},
    {"title": "Business Partnership Warning", "body": "Before you sign that contract, check if your new partner's chart brings you massive luck or total ruin.", "category": "career_business"},
    {"title": "The Entrepreneur's Spark", "body": "Do you have the risk-taking planets needed for a successful startup? Find out before you quit your day job.", "category": "career_business"},
    {"title": "Hidden Enemy at Work", "body": "Someone in your office is plotting against you. Use astrology to identify and neutralize workplace politics.", "category": "career_business"},
    {"title": "Your Ultimate Power Year", "body": "Every career has a peak. Discover the exact year you will achieve your highest professional success!", "category": "career_business"},
    {"title": "Sade Sati Alert!", "body": "Is Saturn secretly ruining your life right now? Find out if you are under the dreaded Sade Sati and how to survive it.", "category": "timing_transits"},
    {"title": "The Golden Window", "body": "Jupiter is entering your luck sector, but only for a few short months! Don't miss this incredibly rare opportunity.", "category": "timing_transits"},
    {"title": "Rahu's Illusion", "body": "Are you making a massive mistake right now? Check if Rahu is clouding your judgment before it's too late.", "category": "timing_transits"},
    {"title": "The Life-Changing Eclipse", "body": "The upcoming eclipse will drastically alter one specific area of your life. Find out which one before it hits!", "category": "timing_transits"},
    {"title": "Retrograde Warning", "body": "Mercury retrograde is coming to crash your plans. See how to protect your communications, travel, and gadgets.", "category": "timing_transits"},
    {"title": "Your Lucky Day", "body": "You have one extremely lucky day this month. Know when it is so you don't waste it sitting on the couch!", "category": "timing_transits"},
    {"title": "Ending Bad Karma", "body": "Your most difficult planetary period is finally ending. Find out the exact date your life is about to get easier.", "category": "timing_transits"},
    {"title": "The Wealth Transit", "body": "Venus is blessing your money house. Here is what you need to do today to maximize the cash flow.", "category": "timing_transits"},
    {"title": "Danger Zone", "body": "Mars is casting a risky aspect on your chart. Know what activities to strictly avoid this week to stay safe.", "category": "timing_transits"},
    {"title": "Mid-life Awakening", "body": "Approaching your Saturn Return? Prepare for the biggest transformation of your life before it catches you off guard.", "category": "timing_transits"},
    {"title": "Past Life Karma", "body": "Why do you keep facing the exact same problems? Uncover the past-life debts holding you back in this birth.", "category": "hidden_traits_karma"},
    {"title": "Your Hidden Talent", "body": "You have a secret skill that could make you millions, but your chart says you are completely ignoring it.", "category": "hidden_traits_karma"},
    {"title": "The Intuition Mark", "body": "Are you naturally psychic? Check your chart for the mystic placements that grant a powerful sixth sense.", "category": "hidden_traits_karma"},
    {"title": "Master Numbers", "body": "Does your birth date hold a hidden numerology code for extreme success? Let's decode it before your birthday.", "category": "hidden_traits_karma"},
    {"title": "Your Spirit Guide", "body": "Which cosmic energy is protecting you? Find your Ishta Devata for ultimate peace, protection, and success.", "category": "hidden_traits_karma"},
    {"title": "Foreign Land Calling", "body": "Does your chart say you belong in another country? Find out if your fortune actually lies across the ocean.", "category": "hidden_traits_karma"},
    {"title": "Ancestral Blessings", "body": "Are your ancestors angry or blessing you? Check for Pitra Dosha and clear the invisible obstacles in your path.", "category": "hidden_traits_karma"},
    {"title": "Gemstone Magic", "body": "You might be wearing the wrong colors! Discover the one gemstone that can instantly turn your luck around.", "category": "hidden_traits_karma"},
    {"title": "Avoid These Dates!", "body": "Every month has highly inauspicious dates for your specific zodiac sign. Note them down before planning anything big.", "category": "hidden_traits_karma"},
    {"title": "Your Ultimate Destiny", "body": "What is the main purpose of your birth? Stop wandering aimlessly and find out what you were truly born to do.", "category": "hidden_traits_karma"},
]
